### ISSUE TITLE
Loading assets should be done on a dedicated thread

### ISSUE THREAD

**Issue by loopier** [loopier/animatron#31]
Load assets freezes the app until they are fully loaded. This is not a desired behaviour.

Assets should probably be loaded on a different thread. Right?

There's an issue in Godot's repo talking about this: https://github.com/godotengine/godot/issues/55566

**Comment by loopier** [comment]
I found [this video](https://www.youtube.com/watch?v=3r7IohvVnw8) that seems to address this issue.

It creates a cache array where images are loaded, then they are already in memory and can be used elsewhere.

**Comment by loopier** [comment]
Maybe what we need is [WorkerThreadPool](https://docs.godotengine.org/en/stable/classes/class_workerthreadpool.html).

**Comment by totalgee** [comment]
Yes, something like that will work well for this.

**Comment by loopier** [comment]
Solved in https://github.com/loopier/animatron/commit/af185254625050db1a47afafa7fe1e0ecff43eeb
