### ISSUE TITLE
OSC doesn't work

### ISSUE THREAD

**Issue by loopier** [loopier/animatron#36]
OSC stopped working at some point.

I had to make [a hack](639367c3c7780596c58e49b21f17b9c946cc081d) to get OSC to work.

**Comment by loopier** [comment]
Solved (I think) in https://github.com/loopier/animatron/commit/f9191cbfc6425fbff73fb57821d0a62604c3b83c

**Comment by loopier** [comment]
@totalgee suggested that this should work withouth OscReceiver being a Node. 

So I'm undoing it and reopening the issue.

The object is added as a child in [this line](https://github.com/loopier/animatron/blob/bc3bb4ff68d089670c0b1cac9c233750222b22b6/Main.gd#L43) but it's not working. We need to find out why.

**Comment by loopier** [comment]
I posted the question on [Godot's forum](https://forum.godotengine.org/t/physics-process-not-called-in-non-node-custom-class/56982).

**Comment by totalgee** [comment]
You can't add it as a child if it's not some kind of Node, the deferred add_child probably fails. In the _physics_process() for Main you could just call the OscReceiver method to get messages.

**Comment by totalgee** [comment]
Or, make it extend Node. In fact, I see that is how the code is in develop, whereas in main branch it does not extend Node. That's likely why one is working and the other not.

**Comment by loopier** [comment]
Yes, I changed it in develop to see if it worked, but you suggested OscReceiver should not be a Node (or so I recall).

I tried also calling `_physics_process` from `Main` but that slowed down the app. Should we then just convert `OscReceiver` to Node?  Why did it work before, then?

**Comment by loopier** [comment]
> Or, make it extend Node. In fact, I see that is how the code is in develop, whereas in main branch it does not extend Node. That's likely why one is working and the other not.

OK, I'll leave it as a node, then, as fixed in f9191cb
