### ISSUE TITLE
Support Actor colour modulation (as well as the current addition behaviour)

### ISSUE THREAD

**Issue by totalgee** [loopier/animatron#55]
It would be very useful to be able to use the built-in modulation colour for Sprites. This is more useful than addition (which we currently support) when you have mostly black & white images, or greyscales, because modulation (multiplication) by a colour gives you a shade of that colour.

The current additive behaviour is useful when you have very dark things, or sprites that have pure black in some components (like a pure green or blue sprite...you can multiply it by red all you want by it won't turn red). So both addition and multiplication of colours are useful in different cases, but likely modulation would be more what people would expect.

**Comment by totalgee** [comment]
Resolved by 8bfc873. The `/color` behaviour is now to modulate, and there is a new command `/color/add` to...add.

**Comment by loopier** [comment]
Cool!

Would you mind posting some examples? I'm a bit lost with the multiplying vs. adding you are saying...
